### ISSUE TITLE
Rows with MIDI slots cannot be exported to arrangement  (From Matrix sequencer neither)

### ISSUE THREAD

**Issue by atencion** [helgoboss/helgobox#1117] opened 2024-08-20 11:53 UTC
**Describe the bug**
I get an error when trying to export rows with MIDI slots to arrangement  It happens the same with recorded Matrix sequences.

**To Reproduce**
1. Record a MIDI Clip into a Slot
2. Click on the row and select "Export Row To Arrangement"
3. A Pop up with an error appears (pasted below)
4. This doesnt seem to happen when there are only audio clips in the row.

**Expected behavior**
It should export the clips in the row to the arrangement as expected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Here`s the log.

===== ATTENTION =====

Sorry, an unknown error occurred in REAPER plug-in Helgobox. REAPER should continue to work but Helgobox might show unexpected behavior until restarting REAPER. If you feel like saving your project file at this point, better save it as a new file because this error could have messed up the plug-in state. 

In any case, please report this error:

1. Prepare an e-mail containing:
    - The error information further below (IMPORTANT)
    - Some instructions on how to reproduce the error (IMPORTANT)
2. If possible, attach the following files: 
    - Your REAPER project file (.rpp)
    - Your REAPER configuration file (reaper.ini)
3. Send it to info@helgoboss.org

Thank you for your support!

--- cut ---
REAPER version:      7.20/x64
Module name:         Helgobox
Module version:      v2.16.1/x86_64 rev 59b056 (2024-08-09 10:39:55 UTC)
Module base address: 0x7ffe3c100000
Module size:         0x2754000

Message: not implemented

   0:     0x7ffe3d761cdb - invoke_host
   1:     0x7ffe3d75f9f2 - invoke_host
   2:     0x7ffe3d6d0aeb - invoke_host
   3:     0x7ffe3d96b0c7 - cpp_to_rust_ProjectStateContext_SetTempFlag
   4:     0x7ffe3d96af19 - cpp_to_rust_ProjectStateContext_SetTempFlag
   5:     0x7ffe3d96933f - cpp_to_rust_ProjectStateContext_SetTempFlag
   6:     0x7ffe3d96ac08 - cpp_to_rust_ProjectStateContext_SetTempFlag
   7:     0x7ffe3dc5bb74 - cpp_to_rust_ProjectStateContext_SetTempFlag
   8:     0x7ffe3dc5bc3d - cpp_to_rust_ProjectStateContext_SetTempFlag
   9:     0x7ffe3d5ace27 - invoke_host
  10:     0x7ffe3d4e9965 - invoke_host
  11:     0x7ffe3d553129 - invoke_host
  12:     0x7ffe3d552768 - invoke_host
  13:     0x7ffe3d551e5c - invoke_host
  14:     0x7ffe3d5519a3 - invoke_host
  15:     0x7ffe3cbe011d - MAIN
  16:     0x7ffe3c7ae13d - NSEEL_HOSTSTUB_LeaveMutex
  17:     0x7ffe3d08eb5f - invoke_host
  18:     0x7ffe3cc14b2a - invoke_host
  19:     0x7ffe3c9bb353 - DllMain
  20:     0x7ffe3d6f89b3 - invoke_host
  21:     0x7ffe3c612cc6 - NSEEL_HOSTSTUB_LeaveMutex
  22:     0x7ffe3d82f2ff - cpp_to_rust_ProjectStateContext_SetTempFlag
  23:     0x7ffe3d811c83 - cpp_to_rust_IReaperControlSurface_Run
  24:        0x140330f0b - <unknown>
  25:        0x14020319b - <unknown>
  26:        0x1402028ca - <unknown>
  27:        0x1402020d3 - <unknown>
  28:        0x1404bcea1 - <unknown>
  29:     0x7fff3ebf3170 - ScreenToClient
  30:     0x7fff3ebf2912 - ScreenToClient
  31:     0x7fff3ec39ec9 - UnpackDDElParam
  32:     0x7fff3ebeef5c - CallWindowProcW
  33:     0x7fff3ebee684 - DispatchMessageW
  34:        0x1404b3dd0 - <unknown>
  35:        0x140aac661 - <unknown>
  36:     0x7fff3d867374 - BaseThreadInitThunk
  37:     0x7fff3f73cc91 - RtlUserThreadStart
--- cut ---

**Comment by helgoboss** [comment] 2024-08-20 12:21
Duplicate of already fixed #1098

**Closed by helgoboss** 2024-08-20 12:21 UTC
