### ISSUE TITLE
Playtime2 records without applying Input FX

### ISSUE THREAD

**Issue by askoriy** [helgoboss/helgobox#1338] opened 2024-11-28 00:00 UTC
**Describe the bug**
I use Input FX (custom JS effect) to tune the velocity and transpose the notes from midi keyboard before recording.
When record directly in Reaper, recorded notes already have been processed as expected.
When record in Playtime, during recording notes are processed, but during playback the cell the original notes are played (without FX)
I didn't tested with audio Input FX

**To Reproduce**
1. Run Playtime and add track
2. Arm the track, select midi source, add input FX  JS "MIDI Transpose Notes", move transpose slider.
3. Record the cell. You should hear transposed notes while playing the keyboard
4. Play the recorded cell. You will hear original not transposed notes

**Expected behavior**
Apply Input FX before recording, record the result of processing Input FX

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Reaper 7.27
 - Playtime v2.16.14

**Comment by helgoboss** [comment] 2024-11-28 08:56
Hi, this is not a bug. It's just not supported. There has been another recent discussion about this somewhere here.

If you need that, please open a feature request. Can't promise though if that will ever be supported, because it would need a slightly different technical approach.

Closing.

**Closed** 2024-11-28 08:59 UTC
