### ISSUE TITLE
Playtime: GUI bug when resizing Playtime window

### ISSUE THREAD

**Issue by dnull** [helgoboss/helgobox#935] opened 2024-07-18 20:29 UTC
My REAPER project shows a bug when resizing the Playtime window. This bug is tied to a specific REAPER project (see attachment in step 1). I was unfortunately not able to deliberately produce a second REAPER project which shows the same bug.

### Versions
Helgobox 2.16.0 #0 (also observed with 2.16.0-pre.18)
REAPER v7.18

### Steps to reproduce:
1. Load the attached project in REAPER ([2024-07-16 Session 1.zip](https://github.com/user-attachments/files/16288887/2024-07-16.Session.1.zip))
2. Click on button "Show Playtime".
![grafik](https://github.com/user-attachments/assets/6470c26a-c923-47f1-9a55-5cd0de3abfcb)
4. Click on the full screen button of the Playtime window.
![grafik](https://github.com/user-attachments/assets/afac2c3a-d313-43b3-a2b9-1050b683c053)

### Expected behaviour:
The Playtime window is shown in full screen and can be used.

### Actual behaviour:
The window flickers for a moment but is not shown in full screen. Instead, it is displayed with a trimmed border and all mouse inputs are received by the underlying REAPER window. This situation can be resolved by a second click on the "Show Playtime" button, after which Playtime works normally and can be successfully resized to full screen.

![reaper_eJrdgqdX0v](https://github.com/user-attachments/assets/4ec80817-58b8-4cc7-88d2-78d55a24092e)

**Comment by helgoboss** [comment] 2024-07-19 06:45
Thanks for the report, I will look into it as soon as possible.

**Comment by atencion** [comment] 2024-07-20 16:00
Yes, same strange behabiour here. No matter what project I^m on.  Thanks!

**Comment by helgoboss** [comment] 2024-07-23 12:33
Probably connected: (Re)opening app on Windows sometimes shows blank window. I should look at this as well. Treating it as the same issue for now.

**Comment by helgoboss** [comment] 2024-07-25 11:55
I was able to reproduce it. Trying to find the cause.

**Comment by helgoboss** [comment] 2024-07-25 16:04
This happens on Windows only and is related to restoring full-screen mode right upon opening the window.

My solution: Not restoring full-screen mode when being on Windows. It's not a big loss. It just means that you manually need to go into full-screen again after you force-closed the window (via X button or by closing project/REAPER) and reopened it. There's still the Strg+Shift+P action/shortcut which just shows/hides the window instead of force-closing it, correctly restoring full-screen mode.

**Closed by helgoboss** 2024-07-25 16:04 UTC
Labels: bug, app, playtime
