### ISSUE TITLE
need better distinction between FX parameters and compartment parameters throughout

### ISSUE THREAD

**Issue by mangowannamango** [helgoboss/helgobox#1080] opened 2024-08-07 20:38 UTC
The difference between FX parameters and compartment parameters could be made more clear. I read about them both in the user guide pretty early on, but was confused. By the time I needed that knowledge, I had forgotten what little I did understand.

 It took me days of bashing my head against the wall to find this answer: 
 https://forum.cockos.com/showpost.php?p=2796080&postcount=4350

Before I found that solution, my issue was this (copy-pasted from reaper forum):
_"Hi Benjamin. I'd like help figuring out units, what they're for, and why they seem to be messing with my conditional activation.
I followed your user guide section 5.1 and 5.2, and it worked perfectly. Then, for my own exploratory purposes, I tried copying over my mappings and groups to another unit in the same instance, and now the previous/next buttons will not properly switch groups. I tried everything I could think of, mostly to ensure that unit 1 wasn't interfering with unit 2: I tried rebinding sources, using parameter 2 instead of parameter 1, emptying unit 1 of bindings, restarting Reaper, etc. Nothing worked."_

I knew something must be wrong because everything was exactly the same as it was in unit 1, except for the fact that it wasn't working.

So, my request is that the "edit group" box distinguish between compartment parameters and instance parameters, or FX parameters or whatever the heck they're called. See, I can't keep it straight. One of them is built-in to all Reaper VSTs and one is native to ReaLearn, is that correct? There's no indication of that in ReaLearn itself. I may never have found this out without the forum, which is a sign that something in the UI is not optimal.

Also, it's just a shame that "only the compartment parameters from the main unit can be controlled from outside (and therefore also from inside from another unit)". Can anything be done about this, or is that out of your domain?

And what's the point of using a unit as opposed to a sub-instance, if units are inherently less powerful (and so far, way more complicated)? I assume units were made as a partial replacement, but I'm not sure why. Also your user guide refers in many places to **instances** while it should be updated to **units** (unless I'm mistaken). Example: The user guide speaks of "instance-wide FX to preset links", but my version of ReaLearn only shows unit-wide or global as an option for that  whole link-y thingamajig (which is also confusing, and I wish it had a routing matrix, but that's another topic. Maybe that's what the pot browser will be for?)

_Originally posted by @mangowannamango in https://github.com/helgoboss/helgobox/discussions/1079_

**Comment by helgoboss** [comment] 2024-08-08 17:20
> So, my request is that the "edit group" box distinguish between compartment parameters and instance parameters, or FX parameters or whatever the heck they're called. See, I can't keep it straight. One of them is built-in to all Reaper VSTs and one is native to ReaLearn, is that correct? There's no indication of that in ReaLearn itself. I may never have found this out without the forum, which is a sign that something in the UI is not optimal.

The problem is that the user guide is not up-to-date in this respect (see my other answer). Units are not mentioned there yet and without units, there's virtually no difference between FX and compartment parameters. With Units, there is.

The short version:

- A Unit is like a mini instance of ReaLearn within a Helgobox FX instance.
- Each Unit has its own set of compartment parameters (both controller and main compartment parameters)
- Only the main unit (the first one) has its compartment parameters exposed as FX parameters

> Also, it's just a shame that "only the compartment parameters from the main unit can be controlled from outside (and therefore also from inside from another unit)". Can anything be done about this, or is that out of your domain?

The FX parameter list of a Helgobox instance could get huge if you have many units. That can be lead to performance issues, especially in the REAPER GUI. It can also become complex in situations when you e.g. remove a unit in the middle. In order avoid complexity (ReaLearn already has enough of that), I decided to only let the first unit be accessible "from the outside".

What's your use case that requires internal units to be accessible via FX parameters?

> And what's the point of using a unit as opposed to a sub-instance, if units are inherently less powerful (and so far, way more complicated)? I assume units were made as a partial replacement, but I'm not sure why.

For years, I preached "Add one instance per controller". And it was enough. But Playtime and Pot Browser came into existence, as part of Helgobox. It was necessary to find a way to control one Playtime instance with multiple controllers. Instead of requiring a complex setup where multiple Helgobox instances (one per controller) point to one main Helgobox instance (the one with a Playtime instance), I decided to introduce a much simpler concept: One Helgobox instance has one Playtime instance and can have arbitrarily many units that may control (don't have to) the Playtime instance in that Helgobox instance.

Advantages:

- Easy setup when using Playtime and/or Pot Browser (as described, the original motivation)
- In many cases, you can now put your complete setup into just one Helgobox instance. Easier to handle, less clunky.
- The ability to export/import/share the **complete** state of that one instance including all controllers.

> Also your user guide refers in many places to **instances** while it should be updated to **units** (unless I'm mistaken). Example: The user guide speaks of "instance-wide FX to preset links", but my version of ReaLearn only shows unit-wide or global as an option for that whole link-y thingamajig (which is also confusing, and I wish it had a routing matrix, but that's another topic. Maybe that's what the pot browser will be for?)

Because the user guide is not up-to-date (see "Last update of text:" after table of contents).

**Comment by mangowannamango** [comment] 2024-08-10 16:06
Ah, I see. Makes sense why you wouldn't make the parameters list super long. So, basically, I shouldn't use units if I want to be able to activate/deactivate them from outside or anything like that? It'd be nice if there were a way to do this with a target called : "Enable/disable units" (based on their unique tags, which they already have). That way you could at least turn them on and off without needing to mess with parameters, yea?
Also, being able to browse which unit is visible with a mapping might be nice. Less urgent though.

My use case for trying to do that is that I had one ReaLearn instance for my one controller on a vital track, and a different unit for each preset (via unit-to-fx preset-link). At least, that's how it was supposed to work. Maybe it still could. But I couldn't find a way to switch between them with a bank browse/previous/next type of mapping. And, of course, I hadn't figured out yet that snapshots were what I really wanted. So, when I figured it out, I split each snapshot preset into a different ReaLearn instance, each with their own main compartment preset, and I am controlling which ones are active/inactive from a main ReaLearn instance on the master track. Now when I switch vital snapshots from ReaLearn, I also get a visual indication of which Instance (renamed to match vital sounds) is selected and which are bypassed. Then, I saved the Vital FX chain.

I'm trying to wrap my head around making a basic FX instance that controls universal settings like bypass, wet/dry, delta solo, track volume/pan, etc. and keeping that instance active when diving into a more specific preset like the ones I am making for Vital, so that my mappings play nicely. This way, I would only have to make the universal settings once (and figure out how to link them to any FX, not a specific one. How?), and from here on, any changes would only be concerned with the new stuff and I wouldn't have to worry about copying over all the core stuff each time. There's probably a fancy programmer word for this. So, I understand the general concept, but I am struggling to figure out how I would do that. Would it be with "make unit superior"? And would I just need to remember which knobs and buttons I bound to the basic instance and make sure I don't use them in my more specific 

I haven't set up my second controller yet. I also haven't tried ReaLearn in other projects so I haven't messed with Monitoring FX chain, but once I do that and load any other FX chains I've saved, I think it should work just fine.

**Comment by helgoboss** [comment] 2024-08-13 06:25
> Ah, I see. Makes sense why you wouldn't make the parameters list super long. So, basically, I shouldn't use units if I want to be able to activate/deactivate them from outside or anything like that? It'd be nice if there were a way to do this with a target called : "Enable/disable units" (based on their unique tags, which they already have). That way you could at least turn them on and off without needing to mess with parameters, yea?

Could be useful in certain scenarios, yes. Although I feel in your scenario it's not necessary. See below. If you still want it, please create a feature request (= new idea in the Idea category).

> My use case for trying to do that is that I had one ReaLearn instance for my one controller on a vital track, and a different unit for each preset (via unit-to-fx preset-link). At least, that's how it was supposed to work. Maybe it still could.

That would be a rather unusual setup. You mention preset-link, so you would switch one unit to "Auto-load". And actually that's the only unit you will need (not one unit per preset). The auto-load mechanism will take care to automatically load the correct preset into that unit depending on which FX is focused (in the foreground). That's why I think you don't need that "Switch unit on/off" thing.

> But I couldn't find a way to switch between them with a bank browse/previous/next type of mapping (which I was trying to do externally). And, of course, I hadn't figured out yet that snapshots were what I really wanted. So, when I figured it out, I split each snapshot preset into a different ReaLearn instance, each with their own main compartment preset, and I am controlling which ones are active/inactive from a main ReaLearn instance on the master track. Now when I switch vital snapshots from ReaLearn, I also get a visual indication of which Instance (renamed to match vital sounds) is selected and which are bypassed. Then, I saved the Vital FX chain.

You mean mapping snapshots (vs. FX snapshots)? If all you want to do is switch your controller to a different setup depending on what FX is "active" (e.g. focused or activated by button presses etc.), then mapping snapshots also seem like a rather unusual way to achieve what. How do you do that? All you need is auto-load.

Damn. I will make an auto-load tutorial during the next days, I thought it's easier to understand.

> I'm trying to wrap my head around making a basic FX instance that controls universal settings like bypass, wet/dry, delta solo, track volume/pan, etc. and keeping that instance active when diving into a more specific preset like the ones I am making for Vital, so that my mappings play nicely. This way, I would only have to make the universal settings once (and figure out how to link them to any FX, not a specific one. How?), and from here on, any changes would only be concerned with the new stuff and I wouldn't have to worry about copying over all the core stuff each time.

Oh yea, definitely. You shouldn't have to copy anything to the specific presets, that would be a massive headache. I'm going to show it's done in the tutorial.

> There's probably a fancy programmer word for this. So, I understand the general concept, but I am struggling to figure out how I would do that. Would it be with "make unit superior"? 

"Make unit superior" - while still useful in certain scenarios involving multiple controllers - is not necessary anymore to achieve something like that. You just need 2 units for that (which can be units within one instance). One for the mappings that stay constant and one for "Auto-load".

> And would I just need to remember which knobs and buttons I bound to the basic instance and make sure I don't use them in my more specific.

Yes, in the auto-loaded (specific) presets, you would need to take care to not to map knobs and buttons that are also used in the constant mappings, otherwise they will do 2 things.

**Comment by helgoboss** [comment] 2024-08-14 06:13
Closing this for now. This sort of thing is better to discuss in the "Discussions" section BTW.

**Closed by helgoboss** 2024-08-14 06:13 UTC
