### ISSUE TITLE
Midi editing is very tedious 

### ISSUE THREAD

**Issue by dissofiddle** [helgoboss/helgobox#1313] opened 2024-11-06 09:27 UTC
Hello,

Playtime is amazing but the main issue that I think would need improvement 
is the midi editing :
-  while editing midi clips is possible and opening the editor 
works well, it is not easy to edit a part away from the beginning of the clip, as 
playtime doesn't seem able for now to resume from a different starting point.
Even worse, changing the edit cursor will likely mute the sound of the current clip.
- a stopped midi clip always show a play cursor running on the clip, which is problematic.
- the play cursor is often visually out of sync

These are the points In my opinion that makes playtime difficult to use in a composition setup.
I understand that audio clip should better be edited in the arrangement of reaper, but it would 
be nice to have these issues for midi fixed. 

regards.

**Comment by helgoboss** [comment] 2024-11-06 09:44
One improvement I can think of in order to avoid the mentioned issues, is the following:

**When Playtime playback is stopped**, Playtime could export the clip to a plain-old MIDI editor item on the column track (maybe even directly visible in REAPER's arrangement). Then you can use REAPER's MIDI editor and REAPER's normal playback to edit the clip to your liking ... so all of those issues would be gone. Playtime could automatically reimport the item into the clip = apply the changes to the clip.

**When Playtime is playing**, proceed as usual. Not sure if it's technically possible to improve that much (the possibilities that REAPER gives to extensions is awesome, but there are a few limits). In the long term, I might actually add my own MIDI editor (#1011), but that's quite some effort and comes with its own pile of issues (e.g. users having to get used to another MIDI editor).

Do you think that would solve your main pain points?

**Comment by helgoboss** [comment] 2024-11-06 11:17
Thought about it a bit further. It probably makes sense to enter this unsynced mode and stop the edited clip permanently, as soon as pressing space to stop global playback. In that mode, one fan freely edit the clip without having to follow Playtime's looping. Playtime would stay in that mode until the user explicitly starts that particular clip again.

**Comment by dissofiddle** [comment] 2024-11-06 11:35
Hello.

indeed, I don't think a plain-old midi editor on the reaper arrangement is the solution. I don't know about the API but my gut feeling is that it will likely induce sync bugs between playtime and the reaper arrangement. 
My only concern is actually convenience : it is okay if play can't resume from the middle of a midi item and have to start again from the start.  I just feel that midi editing is annoying as it seems to stop playback sometimes, and that you have to quit the editor and launch midi clip again. I think the way playtime resume/react with midi edition should be more straightforward, and it's better to feel limited than feel like only half works, ergonomically speaking.
I also noticed that some keyboard shortcuts of playtime seems to interfere with reaper, which is also a weak point in the ergonomy.

**Comment by helgoboss** [comment] 2024-11-06 11:48
> Hello.
> 
> indeed, I don't think a plain-old midi editor on the reaper arrangement is the solution. I don't know about the API but my gut feeling is that it will likely induce sync bugs between playtime and the reaper arrangement.

What kind of sync bugs are you fearing? "Sync" as in out-of-sync timing-wise or "sync" as in not all MIDI data transferred correctly back to the clip?

> My only concern is actually convenience : it is okay if play can't resume from the middle of a midi item and have to start again from the start. I just feel that midi editing is annoying as it seems to stop playback sometimes, and that you have to quit the editor and launch midi clip again.

Could you please make a video which shows that? Or a concrete RPP where this can be reproduced when trying hard enough? 

> I think the way playtime resume/react with midi edition should be more straightforward, and it's better to feel limited than feel like only half works, ergonomically speaking.

Okay, I need to understand what this "half" is that doesn't work in your case. Then I will see if I can do something about it.

**Comment by helgoboss** [comment] 2024-11-12 18:49
@dissofiddle Did you manage to do a short screen recording by any chance? Would really like to look into this bug, ideally before the finally launch.

**Comment by helgoboss** [comment] 2024-12-12 11:07
In the context of this ticket, I'm moving back to the "put MIDI item on original track" approach (and away from the "hidden track" approach). I have outlined the reasons [here](https://github.com/helgoboss/helgobox/discussions/897#discussioncomment-11543061).

**Closed** 2024-12-12 14:04 UTC
Labels: bug, playtime

**Comment by dissofiddle** [comment] 2024-12-20 10:18
Hi Benjamin,

that seems to be a good idea.
Sorry for the late response, work had been crazy lately and I couldn't find
the time to look at the bug I told you about.
I will have a look at it again.
Regards,
Baldwin

Le jeu. 12 déc. 2024 à 15:04, Benjamin Klum ***@***.***> a
écrit :
